#!/usr/bin/env python3
import os
import sys
import random
import subprocess


def main():
    # Random 16 bytes - we could also just read from os.urandom,
    # but this shows how we can call another cmd from this py.
    key = subprocess.run('./rand_key', stdout=subprocess.PIPE).stdout
    while b'\x00' in key:
        key = key.replace(b'\x00', os.urandom(1))

    # Get the plaintext, append and prepend some random bytes.
    plain = sys.stdin.buffer.read()
    before_count = random.randrange(5, 11)
    after_count  = random.randrange(5, 11)
    before = os.urandom(before_count)
    after = os.urandom(after_count)
    plain = before + plain + after

    # Choose a mode to use.
    mode = '-ecb' if random.randrange(0, 2) == 0 else '-cbc'

    cmd, mode, key_str = 'aes', mode, str(key)[1:]
    plain = b'b' * 16
    print(cmd, mode, key_str)
    print(subprocess.run([cmd, mode, key_str], input=plain))
    

if __name__ == '__main__':
    main()
