#!/usr/bin/env python3

import sys
import os

def main():
    inp = sys.stdin.buffer.read()

    if len(inp) % 2 != 0:
        print('must be even len string', file=sys.stderr)
        exit(1)

    half_one = inp[:int(len(inp) / 2)]
    half_two = inp[int(len(inp) / 2):]

    out = bytearray()
    for byte_one, byte_two in zip(half_one, half_two):
        out.append(byte_one ^ byte_two)

    os.write(sys.stdout.fileno(), out)

main()
