#!/usr/bin/env python3

import math
import sys
import os


def _main():
    if '-x' in sys.argv:
        base = 'hex'
    elif '-b' in sys.argv:
        base = 'bin'
    else:
        print('{}: requires -x for hexidecimal or -b for binary'.format(sys.argv[0]), file=sys.stderr)
        exit(1)

    inp = sys.stdin.buffer.read()
    res = to_hex(inp) if base == 'hex' else to_bin(inp)
    sys.stdout.write(res)


def to_hex(inp):
    return _to_base(inp, 16)


def to_bin(inp):
    return _to_base(inp, 2)


def _to_base(inp, base):
    ret = ''
    for b in inp:
        ret += hex(b)[2:].zfill(2) if base == 16 else bin(b)[2:].zfill(8)
    return ret


if __name__ == '__main__':
    _main()

